# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/B_Design/B_Design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==B_Design || ORIG_REF_NAME==B_Design} -quiet] -quiet

# IP: bd/B_Design/ip/B_Design_processing_system7_0_0/B_Design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==B_Design_processing_system7_0_0 || ORIG_REF_NAME==B_Design_processing_system7_0_0} -quiet] -quiet

# IP: bd/B_Design/ip/B_Design_axi_dma_0_0/B_Design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==B_Design_axi_dma_0_0 || ORIG_REF_NAME==B_Design_axi_dma_0_0} -quiet] -quiet

# IP: bd/B_Design/ip/B_Design_ps7_0_axi_periph_0/B_Design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==B_Design_ps7_0_axi_periph_0 || ORIG_REF_NAME==B_Design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/B_Design/ip/B_Design_rst_ps7_0_0M_0/B_Design_rst_ps7_0_0M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==B_Design_rst_ps7_0_0M_0 || ORIG_REF_NAME==B_Design_rst_ps7_0_0M_0} -quiet] -quiet

# IP: bd/B_Design/ip/B_Design_xbar_0/B_Design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==B_Design_xbar_0 || ORIG_REF_NAME==B_Design_xbar_0} -quiet] -quiet

# IP: bd/B_Design/ip/B_Design_axi_mem_intercon_0/B_Design_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==B_Design_axi_mem_intercon_0 || ORIG_REF_NAME==B_Design_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/B_Design/ip/B_Design_AXI_MERGE_v1_0_0_0/B_Design_AXI_MERGE_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==B_Design_AXI_MERGE_v1_0_0_0 || ORIG_REF_NAME==B_Design_AXI_MERGE_v1_0_0_0} -quiet] -quiet

# IP: bd/B_Design/ip/B_Design_auto_pc_0/B_Design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==B_Design_auto_pc_0 || ORIG_REF_NAME==B_Design_auto_pc_0} -quiet] -quiet

# IP: bd/B_Design/ip/B_Design_auto_us_0/B_Design_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==B_Design_auto_us_0 || ORIG_REF_NAME==B_Design_auto_us_0} -quiet] -quiet

# IP: bd/B_Design/ip/B_Design_auto_us_1/B_Design_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==B_Design_auto_us_1 || ORIG_REF_NAME==B_Design_auto_us_1} -quiet] -quiet

# IP: bd/B_Design/ip/B_Design_auto_pc_1/B_Design_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==B_Design_auto_pc_1 || ORIG_REF_NAME==B_Design_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/lotto/Desktop/Consegna/Block_Design/Block_Design.gen/sources_1/bd/B_Design/B_Design_ooc.xdc
