# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lotto/Desktop/Consegna/Block_Design/Block_Design.srcs/sources_1/bd/B_Design/ip/B_Design_processing_system7_0_0/B_Design_processing_system7_0_0.xci
# IP: The module: 'B_Design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lotto/Desktop/Consegna/Block_Design/Block_Design.gen/sources_1/bd/B_Design/ip/B_Design_processing_system7_0_0/B_Design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'B_Design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/lotto/Desktop/Consegna/Block_Design/Block_Design.srcs/sources_1/bd/B_Design/ip/B_Design_processing_system7_0_0/B_Design_processing_system7_0_0.xci
# IP: The module: 'B_Design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lotto/Desktop/Consegna/Block_Design/Block_Design.gen/sources_1/bd/B_Design/ip/B_Design_processing_system7_0_0/B_Design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'B_Design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
